LineLength:
  Max: 100

Documentation:
  Enabled: False

WordArray:
  Enabled: False

Style/RedundantBegin:
  Enabled: False

AllCops:
  Exclude:
    - 'spec/dummy/db/schema.rb'
    - 'spec/dummy/db/migrate/*'

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 20
