language: ruby
rvm:
- 2.1.5
before_install:
- gem install bundler
env:
  global:
  - STORMPATH_APPLICATION_URL=https://api.stormpath.com/v1/applications/4yVIHvHFR77ZyEyFERJgL2
  - secure: BJyo9h7c1w0W65HYHKJ2KS1y5/hfQQb80J/33gvwegXaItmSofZrdpsN3akB4k+Tat5ib3Ge2i1fC8Pfws92H0TOl+4FsW8KNYKoJb44Dba2O+a2Dw/agAUmOYIK1y1GnfYDLp+keF7BH9Kv2sZk3lEcNGQP8KBYS6hLr9SbhHE=
  - secure: KNg3cuDSCqYDGfB8gpYm9WyGecXjuJzAu6EOYDtH5M+FjhtKYoeKG+AO0ffw86fi9ckWXbSrZretxbe09B6xVEHi41b1J6InXCU+ywpym8REHj1/LkR2V41tWKz8Pf6miF6bu3b4fApzau9+o2CfUXHWNzMhWZlD0ysNECOR90s=
  - secure: OWw8Sn31CH0+HGDkWjlxYzOJPm6sbWe+o5lzlQEIklAtaQTHwWujwqPZ95HEam8UTC9YxqsU4aHTdAVRYEXCtVAw4cY/pTd30eoNd6gBV6McxGZcug4ezVpPejof0X6yfz7pC5jzuL3NGYLkX4w8pAl5+yb11hh1HAq0EmGunXo=
