language: ruby
rvm:
- 2.1.5
before_install:
- openssl aes-256-cbc -K $encrypted_57ed81c5c9ab_key -iv $encrypted_57ed81c5c9ab_iv
  -in keypair.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- git config --global user.email "evangelists@stormpath.com"
- git config --global user.name "stormpath-rails documentation"
install:
- gem install bundler
- bundle install --jobs=3 --retry=3
- pip install --user sphinx
script:
- travis_retry rake
# - cd docs
# - make html
# - cd ..
after_success:
- CURRENT_HASH=`git rev-parse HEAD`
- RELEASE_VERSION=`git tag | xargs -I@ git log --format=format:"%ai @%n" -1 @ | sort | awk '{print $4}' | tail -n 1`
- RELEASE_HASH=`git rev-list $RELEASE_VERSION -n 1`
- if [ "$CURRENT_HASH" = "$RELEASE_HASH" ]; then DEPLOY_DOCS=true; fi
#- test -z "$DEPLOY_DOCS" || git clone git@github.com:stormpath/stormpath.github.io.git
#- test -z "$DEPLOY_DOCS" || cd stormpath.github.io
#- test -z "$DEPLOY_DOCS" || git fetch origin source:source
#- test -z "$DEPLOY_DOCS" || git checkout source
#- test -z "$DEPLOY_DOCS" || mkdir -p source/ruby/rails
#- test -z "$DEPLOY_DOCS" || rm -rf source/ruby/rails/latest
#- test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/ruby/rails/latest
#- test -z "$DEPLOY_DOCS" || cp -r ../docs/_build/html source/ruby/rails/$RELEASE_VERSION
#- test -z "$DEPLOY_DOCS" || git add --all
#- test -z "$DEPLOY_DOCS" || git commit -m "stormpath-rails release $RELEASE_VERSION"
#- test -z "$DEPLOY_DOCS" || git push origin source
env:
  global:
  - STORMPATH_APPLICATION_URL=https://api.stormpath.com/v1/applications/4BiS1Hc1LuBEbszdDrOwyz
  - secure: BJyo9h7c1w0W65HYHKJ2KS1y5/hfQQb80J/33gvwegXaItmSofZrdpsN3akB4k+Tat5ib3Ge2i1fC8Pfws92H0TOl+4FsW8KNYKoJb44Dba2O+a2Dw/agAUmOYIK1y1GnfYDLp+keF7BH9Kv2sZk3lEcNGQP8KBYS6hLr9SbhHE=
  - secure: KNg3cuDSCqYDGfB8gpYm9WyGecXjuJzAu6EOYDtH5M+FjhtKYoeKG+AO0ffw86fi9ckWXbSrZretxbe09B6xVEHi41b1J6InXCU+ywpym8REHj1/LkR2V41tWKz8Pf6miF6bu3b4fApzau9+o2CfUXHWNzMhWZlD0ysNECOR90s=
  - secure: OWw8Sn31CH0+HGDkWjlxYzOJPm6sbWe+o5lzlQEIklAtaQTHwWujwqPZ95HEam8UTC9YxqsU4aHTdAVRYEXCtVAw4cY/pTd30eoNd6gBV6McxGZcug4ezVpPejof0X6yfz7pC5jzuL3NGYLkX4w8pAl5+yb11hh1HAq0EmGunXo=
